### ISSUE TITLE
https certificate on mockmyid.com has expired. Please renew

### ISSUE THREAD

**Issue by abstatic** [callahad/mockmyid#14]
Hi, I am using mockmyid services to automate persona testing on a project that I am working on. Just recently the tests, and login with mockmyid credentials stopped working. The error was "timeout error" , Upon visiting the site, I found out that the SSL certificate has expired. I request you to please renew it. Its from letsencrypt, so it should only be a matter of minutes. 

Cheers :+1:

**Comment by callahad** [comment]
Whoops! I guess my Let's Encrypt cronjob didn't work. Will manually fix when I get home today.

In other news, Persona itself [will be shutting down](https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers) at the end of November, so now would be a good time to plan for a replacement. :(

**Comment by abstatic** [comment]
@callahad thanks for the heads up!  I am planning to change the login service to oauth based authentication pretty soon. But for the time being, I need to run tests with every iteration/commit , and momckmyid is very helpful in automating persona login :)

**Comment by callahad** [comment]
Fixed! :) Thanks for the heads up.

Some folks (myself included) are working on a less ambitious spiritual successor to Persona that you might be interested in over at https://github.com/letsauth/letsauth.github.io... hoping to have something to show very, very soon.
